// Single source of truth for every user-facing string on the site.
//
// Why one file: the FAQ text has to appear in TWO places, the visible
// <details> markup and the FAQPage JSON-LD. Google treats a mismatch between
// structured data and rendered text as a structured-data violation, and it is
// the exact kind of drift that survives review because both copies look fine
// in isolation. Rendering both from one array makes the mismatch impossible.
//
// Copy rules that apply to everything in here:
//   - No em dashes. Brand voice rule, applies to all marketing surfaces.
//   - Only claims that are true of the SHIPPED build. A store listing that
//     over-promises is a Play policy problem, not just a credibility one.
//   - Premium is deliberately absent. The freemium entitlement exists in the
//     backend but ships behind HAS_FREEMIUM_ENABLED, which is unset in
//     production, so nothing is purchasable today. Advertising a price nobody
//     can pay would be a misrepresentation. Add it here when the flag flips.
//
// On the word "AI". It is used sparingly and only where it is literally true:
// the chat assistant, and the monthly Discover collections, which are
// generated by an LLM in internal/service/taste_service.go from the user's
// ratings, most-watched genre and most-watched director or actor. It is NOT
// in the H1. "AI movie recommendations" is a real query with real volume, so
// the words have to exist on the page or nothing matches, but this audience
// is also the one most allergic to AI as decoration, and thin AI-hype pages
// are something Google actively demotes. Present and factual beats absent,
// and both beat plastered everywhere.
//
// Text length is split deliberately between two audiences. The feature blocks
// are for someone scrolling on a phone, so they run one short paragraph plus
// three bullets and no more. The FAQ is for someone who came looking for
// detail, and it is also the block that generative search quotes from, so the
// answers there are allowed to be long. Cutting both would cost citations;
// padding both would cost readers.

export const SITE = {
  name: 'I Like Movies',
  domain: 'ilikemovies.app',
  url: 'https://ilikemovies.app',

  // Must match the contact address published in the privacy policy, the terms
  // and the Play Console listing. Four surfaces naming different addresses
  // splits the entity, which is the one signal a small brand cannot afford to
  // fragment. Change this and change all four in the same pass.
  supportEmail: 'hi@ilikemovies.app',

  // Operator jurisdiction, kept identical to the governing-law clause in the
  // published terms. Stating it is an entity signal that search engines and
  // AI answers use to disambiguate a small brand from similarly named ones.
  operatorCountry: 'Netherlands',

  // The definitional sentence. This exact shape (name, category, platforms,
  // price, differentiators, all in one sentence) is what generative search
  // engines lift verbatim when asked "what is X". It is duplicated as the
  // meta description on purpose. "AI assistant" earns its place here because
  // this is the single most-quoted sentence on the site and it is the only
  // one guaranteed to be read.
  definition:
    'I Like Movies is a free movie and TV app for Android with an AI assistant that helps you discover what to watch next, share one library with the people you live with, and keep a record of everything you have seen. An iPhone version is in development.',

  // The meta description is a SEPARATE string, not the definitional sentence.
  // They are built for different readers and cannot be the same text: the
  // definition is optimised for being quoted whole and runs 230 characters,
  // while a search snippet is cut at roughly 155 and would truncate it
  // mid-clause. This one front-loads the terms someone actually types and
  // stops before the cut.
  metaDescription:
    'Free movie and TV app for Android. AI picks from your own ratings, one shared watchlist for your household, and no ads. iPhone version in development.',

  tagline: 'Everything you have watched. Everything you are going to.',

  // Both store URLs. The Android one is correct and permanent; it 404s only
  // until the production listing is approved. The iOS one is null rather than
  // a guessed URL, because the app does not exist on the App Store yet and a
  // fabricated link is worse than a disabled button.
  //
  // The referrer param attributes Play installs back to this website with no
  // JS analytics involved: Play records it verbatim against the install and
  // the value (a URL-encoded utm_source=ilikemovies.app) is readable from the
  // Play Installation Referrer API on first launch. Every link on the site
  // routes through this one constant, so the param reaches every store link
  // without being repeated anywhere.
  playUrl:
    'https://play.google.com/store/apps/details?id=com.moviesagent.app&referrer=utm_source%3Dilikemovies.app',
  appStoreUrl: null as string | null,

  // Root-relative, and on this domain since the migration off
  // sudo-acraciun.github.io/movienight. That host still serves the documents
  // as redirect stubs, because the URL is compiled into every app build that
  // has not taken an over-the-air update, and those installs never stop
  // existing on their own.
  //
  // deleteAccount is the URL in Play Console's data-deletion field, so its
  // slug cannot be renamed here alone.
  legal: {
    privacy: '/privacy',
    terms: '/terms',
    deleteAccount: '/delete-account',
  },
} as const;

// Social profiles the footer links to. Entry rule: a profile appears here only
// once it is LIVE with content. The accounts all exist under @ilikemoviesapp,
// but a footer link to an empty profile reads as abandonment to a visitor, so
// TikTok, Instagram, YouTube and Facebook join this list as each one gets its
// first posts. Deliberately narrower than SAME_AS in index.astro, which is an
// identity claim for crawlers and may name an empty-but-real profile.
export const SOCIALS = [
  { name: 'X', url: 'https://x.com/ilikemoviesapp' },
  { name: 'Reddit', url: 'https://www.reddit.com/r/ilikemoviesapp/' },
] as const;

export type Feature = {
  id: string;
  title: string;
  body: string;
  bullets: string[];
  /**
   * Optional contextual link rendered after the bullets. This is how a
   * homepage section points into the content network without a nav entry:
   * only the discover block carries one today, into /guides.
   */
  link?: { href: string; text: string };
  screenshotAlt: string;
};

// There is no `screenshot` field. Every capture is a real file now, imported
// in index.astro and matched to a block by `id`, so a path string here would
// be a second place for an asset reference to rot. Copy lives in this module,
// assets live with the page that renders them.

// Four blocks, in the order the positioning puts them: discovery, the
// assistant, friends, then the household.
//
// Friends and household are separate sections rather than one "Together"
// block because they are opposite motions. A household is inward facing, the
// people on your sofa sharing one shelf. Friends are outward facing, people
// whose taste you borrow from. Merging them described neither clearly.
//
// There is no tracking block. Its substance lives in CAPABILITIES below, so
// the page stays short without losing the words the category is searched by.
export const FEATURES: Feature[] = [
  {
    id: 'discover',
    title: 'Stop scrolling. Start watching.',
    body: 'The hard part was never finding a film. It is deciding on one before the evening is gone. I Like Movies reads what you actually finish and builds the shortlist from there.',
    bullets: [
      'AI collections drawn from your own ratings, rebuilt every month',
      'Curated tracks for franchises and long-running series, in watch order',
      'See exactly where a title is streaming in your country before you commit',
    ],
    link: { href: '/guides', text: 'Browse the free watch order and comparison guides' },
    screenshotAlt:
      "The I Like Movies discover screen showing AI-generated movie collections built from the viewer's own ratings",
  },
  {
    id: 'assistant',
    title: 'Describe the night. Get the film.',
    body: 'Search needs a title. Conversation does not. Ask for something short and funny for a Tuesday, or the one with the submarine and the cook, and the AI assistant comes back with real titles you can stream tonight.',
    bullets: [
      'Ask in plain language, by mood, plot fragment, or half-remembered scene',
      'Answers know your history, so nothing you have already seen comes back',
      'Send a voice message or a photo of a list and it reads the titles for you',
    ],
    screenshotAlt:
      'The AI chat assistant in I Like Movies answering a request for a film recommendation with real titles',
  },
  {
    id: 'friends',
    title: 'Your friends have better taste than an algorithm.',
    body: 'The best recommendation you ever got came from a person, not a homepage row. Follow the people whose taste you trust, see what they are watching, and take what looks good.',
    bullets: [
      'Follow friends and see what they are watching and rating right now',
      'Compare taste to find where you overlap and where you never will',
      'Share any title straight into a chat, and it opens in their app',
    ],
    screenshotAlt:
      'The I Like Movies social feed showing a friend adding a series to their watchlist and another rating a film, each with likes and replies underneath',
  },
  {
    id: 'household',
    // "shared watchlist" is deliberate. It was "One shelf for the whole
    // sofa", which is a nicer line and says nothing a search engine can use.
    // "shared watchlist app" is a real query with real intent, and headings
    // carry more weight than body copy, so the noun belongs in the H2 rather
    // than three sentences below it.
    title: 'One shared watchlist for the whole sofa.',
    body: 'Two people, two watchlists, and a half-finished series nobody can agree on. A household puts everyone you live with on one library, so what you add, they see.',
    bullets: [
      'A household shares one watchlist and one watched history',
      'Add a film on your phone and it is on theirs before you sit down',
      'No more working out which of you saved the film worth watching',
    ],
    screenshotAlt:
      "A shared household watchlist in I Like Movies, grouped by member, with each person's saved films listed under their name",
  },
];

// Secondary features, rendered as small cards. This grid carries the tracking
// vocabulary that used to sit in its own section: "movie tracking", "episode
// tracking", "ratings", "notes", "import". Tracking is the head term the whole
// category is searched by, so the words have to exist in body text somewhere
// even though the section they came from was cut for length.
//
// NINE entries, not eight. The grid resolves to three columns at desktop
// width, so any count that is not a multiple of three leaves a visibly
// unfinished last row.
export const CAPABILITIES = [
  {
    title: 'One library, films and TV',
    body: 'Films and TV are tracked in one place, with a single history and a single watchlist, rather than two apps fighting over your evening.',
  },
  {
    title: 'Episode tracking',
    body: 'Mark individual episodes, see how far into a season you are, and get told when a series has actually ended.',
  },
  {
    title: 'Ratings and private notes',
    body: 'Rate out of five stars and keep a note on anything, including rewatches. The note is yours, not a public review.',
  },
  {
    title: 'Streaming availability',
    body: 'See which services carry a title in your country, checked per region rather than assumed from a US catalogue.',
  },
  {
    title: 'Your own lists',
    body: 'Build lists for a marathon, a genre, a director, or an evening. No fixed categories to fight against.',
  },
  {
    title: 'Import your history',
    body: 'A Letterboxd .zip export or an IMDb .csv export uploads directly, ratings and watchlist included.',
  },
  {
    // No mention of badges. The badge code, the /badges route and GET_BADGES
    // all still exist, but SHOW_BADGES_ENTRY is false in the mobile app, so
    // there is no way for a user to reach the screen. Every claim below maps
    // to a field on ProfileStats or CountryStats that renders today.
    title: 'Your viewing profile',
    body: 'Your profile totals the hours you have watched and your average rating, works out your top genres, breaks your history down by the country a film came from, and pins your top four films.',
  },
  {
    title: 'No ads, ever',
    body: 'No advertising, no sponsored rows, no engagement feed. The recommendations answer to you.',
  },
  {
    title: 'Everywhere you sign in',
    body: 'Your library lives on the server, not the handset, so it follows you to a new phone without an export.',
  },
];

/** Answers are paragraphs, not one block. See the note on FAQS below. */
export type Faq = { q: string; a: string[] };

// The single highest-value block for generative search, because AI answers are
// assembled from question-shaped content.
//
// Two rules hold across every answer.
//
// First, the opening sentence answers the question completely and stands
// alone. An answer that builds up to its point is useless to a machine that
// lifts one sentence, and a two-line answer gets paraphrased rather than
// quoted. A paraphrase is not a citation.
//
// Second, answers are ARRAYS of paragraphs. A five-sentence wall is where a
// human reader gives up, and the break costs nothing in structured data: the
// JSON-LD joins the paragraphs back into one string, so the words a crawler
// sees are identical to the words on screen. Readability and quotability are
// not actually in tension here, they just need different markup.
export const FAQS: Faq[] = [
  {
    // First on purpose, and the answer opens with SITE.definition verbatim:
    // "What is I Like Movies?" is the exact question an answer engine asks
    // about an entity it does not recognise, and the definitional sentence
    // was written to be lifted whole. One string, two surfaces, no drift.
    q: 'What is I Like Movies?',
    a: [
      SITE.definition,
      'You rate what you watch, and both the monthly Discover collections and the chat assistant work from that history, so the suggestions are drawn from your own taste rather than a general popularity chart.',
    ],
  },
  {
    q: 'Is I Like Movies free?',
    a: [
      'Yes. I Like Movies is free to download and free to use, with no advertising and no sponsored recommendations.',
      // Deliberately silent on limits, per the decision not to advertise the
      // free-tier assistant cap. This previously read "no feature that stops
      // working after a set number of films", which was an affirmative claim
      // that there are no caps. Not mentioning a limit is a positioning
      // choice; stating that none exists would not be, so the clause is gone
      // rather than restored.
      'There is no trial period that expires, and the recommendations are generated from your own ratings and viewing history rather than from anything a studio or streaming service has paid to promote.',
    ],
  },
  {
    // "movies" not "films" in the question, deliberately. Body copy can use
    // either, but an FAQ question is a query-matching asset and "movie
    // recommendations" is searched far more than "film recommendations".
    q: 'Does I Like Movies use AI to recommend movies?',
    a: [
      'Yes, in two places. The Discover tab builds collections for you each month using an AI model that reads your ratings, your most-watched genre and the director or actor you return to most, and the in-app assistant answers requests for something to watch in plain language.',
      'The AI works from your own viewing history rather than from a general popularity chart, which is why the suggestions change as your ratings do. It also knows what you have already seen, so a film you have watched does not come back around.',
      'Everything else in the app is ordinary software. Your ratings, lists, watch history and streaming availability are recorded and looked up directly, not guessed at.',
    ],
  },
  {
    q: 'Which platforms does I Like Movies run on?',
    a: [
      'I Like Movies is available for Android on Google Play. An iOS version for iPhone is in development and is not on the App Store yet.',
      'Your library is stored on the server rather than on the handset, so when the iOS version arrives you will sign in to the same account and find everything already there. The same is true if you replace your Android phone.',
    ],
  },
  {
    q: 'Can I import my Letterboxd history into I Like Movies?',
    a: [
      'Yes. Request a data export from Letterboxd, which arrives as a .zip file, then upload that file in the app under Imports.',
      'Your ratings, watched films and watchlist are read from the export and matched against the film database, so a library built over years transfers in a few taps rather than being retyped. Nothing is sent back to Letterboxd and your account there is unaffected.',
    ],
  },
  {
    q: 'Can I import my IMDb ratings and watchlist?',
    a: [
      'Yes. Export your ratings or a list from IMDb as a .csv file and upload it in the app under Imports.',
      'The app works out on its own whether the file is a watchlist or a custom list, and asks you only when the file itself is ambiguous, because IMDb does not record a list name inside the export. Ratings come across with the titles, so your scores are preserved rather than reset.',
    ],
  },
  {
    q: 'Can two people share one watchlist?',
    a: [
      'Yes. A household in I Like Movies is a shared library for the people you live with, and everyone in it sees the same watchlist and the same watched history.',
      'A film added by one person shows up for everyone without being sent or shared manually. It is built for the case where two people keep separate lists and then cannot remember which of them had the film worth watching.',
    ],
  },
  {
    q: 'Can I follow friends and see what they are watching?',
    a: [
      'Yes. You can follow other people using the app and see what they are watching, what they have rated, and what they have added to their lists.',
      'Comparing taste with someone shows where your histories overlap, which is usually a faster route to a good recommendation than any algorithm manages.',
      'Following someone is separate from a household. Friends keep their own libraries; a household shares one.',
    ],
  },
  {
    q: 'Does I Like Movies track TV shows and individual episodes?',
    a: [
      'Yes. TV series are tracked at episode level, so the app records exactly which episodes you have watched and how far into a season you are.',
      'Films and series live in the same library rather than in separate sections, which means a single history covers both. The app also distinguishes a series that has ended from one that is between seasons, so a finished show stops behaving like something you are behind on.',
    ],
  },
  {
    q: 'Does I Like Movies show where a movie is streaming?',
    a: [
      'Yes. Each title lists the streaming services that carry it in your country.',
      'Availability is resolved for your region rather than taken from a single global catalogue, which matters because the same film sits on different services in different countries and often on none. Checking before you commit is the difference between starting a film and spending twenty minutes finding out you cannot.',
    ],
  },
  {
    q: 'What is the assistant in I Like Movies?',
    a: [
      'It is an AI chat you can ask for recommendations in your own words, by mood, by a fragment of a plot, or by naming a film you liked.',
      'It reads your watch history, so it does not suggest something you have already seen, and it answers with titles that are actually available in your region.',
      'You can also send it a voice message, or a photo of a list of titles, and it will read them.',
    ],
  },
  {
    q: 'Does I Like Movies work offline?',
    a: [
      'No. I Like Movies needs an internet connection.',
      'Your library syncs across your devices and your household, and film data including streaming availability is fetched live rather than bundled into the app. There is no offline mode and no local-only library.',
    ],
  },
];

export type Migration = {
  name: string;
  /** How an existing library moves across, or why it does not need to. */
  move: string;
  /** What is different once they are here. Factual, no disparagement. */
  changes: string;
  /**
   * Deep link to the full standalone page for this competitor, where one
   * exists (/vs/<slug> or the TV Time guide). IMDb has no such page, so the
   * field is optional and its row renders without a link.
   */
  compare?: { href: string; label: string };
};

// Framed as migration help rather than a scorecard.
//
// This section exists for search reasons that are worth stating plainly: a new
// domain will not rank for "movie tracker app" against Letterboxd, Trakt and
// IMDb. The queries it can win are comparative and long tail, and those only
// match a page where the competitor is named. Comparison content is also
// disproportionately quoted by generative search.
//
// The framing matters as much as the content. Written as "we beat them" it
// reads petty, and a hostile framing gets quoted just as readily as a helpful
// one. Written as "here is how you move across and what changes", the same
// competitor names carry the same query match while the content is actually
// useful to the person reading it.
export const MIGRATIONS: Migration[] = [
  {
    name: 'Coming from Letterboxd',
    move: 'Request your data export, which arrives as a .zip, and upload it under Imports. Ratings, watched films and your watchlist come across together.',
    changes:
      'Letterboxd is built around public reviews and film criticism as a social activity. Here your notes are private by default, TV series are tracked alongside films at episode level, streaming availability is shown for your country, an AI assistant answers in plain language, and the people you live with can share a single library.',
    compare: { href: '/vs/letterboxd', label: 'Read the full Letterboxd comparison' },
  },
  {
    // IMDb belongs here and belongs high. It has a larger user base than the
    // other three put together, "export IMDb ratings" is a live query, and it
    // is one of only two sources with a real import path in the app. Ordered
    // second so the two rows that CAN import sit together at the top.
    name: 'Coming from IMDb',
    move: 'Export your ratings or your watchlist from IMDb as a .csv and upload it under Imports. The app works out which kind of list the file is on its own.',
    changes:
      'IMDb is a reference database with a watchlist attached, and it is still the best place to look up who directed what. This is built for the other half of the problem: choosing something tonight and keeping the record afterwards, with recommendations drawn from your own ratings, streaming availability for your country, and a library your household shares.',
    compare: { href: '/vs/imdb', label: 'Read the full IMDb comparison' },
  },
  {
    name: 'Coming from Trakt',
    move: 'There is no Trakt import. Imports read a Letterboxd .zip or an IMDb .csv, and a Trakt export is neither, so a Trakt library starts fresh here and rebuilds itself as you use the app. Marking a season watched takes a tap.',
    changes:
      'Trakt is built around automatic scrobbling from media servers and players, and it is very good at that. This is a phone app with nothing to install alongside it, aimed at the moment before you press play rather than the record of having pressed it.',
    compare: { href: '/vs/trakt', label: 'Read the full Trakt comparison' },
  },
  {
    name: 'Coming from TV Time',
    move: 'TV Time closed on 15 July 2026, and there is no TV Time import here, so series progress is set as you go. Marking a season watched takes a tap.',
    changes:
      'TV Time was focused on episode tracking and reminders for series. Episodes are tracked one at a time here too, films and TV sit in one library rather than being two separate concerns, discovery comes first, there is no advertising, and a household shares a single library instead of everyone keeping their own.',
    compare: { href: '/from-tv-time', label: 'Read the full guide to life after TV Time' },
  },
];
